### PR TITLE
Fixed Overflow in decoding

### LINKED ISSUE #48: Multiplication overflow
Caught by the fuzz tests:

https://github.com/bschwind/mqtt-broker/blob/9037df21e08a11fc2634609408d5aa539d3fe13f/mqtt-v5/src/decoder.rs#L103-L105

### PR DESCRIPTION
**Pull request by Nereuxofficial**
Hey i took the liberty to fuzz this crate as i need it for a personal Project and fixed the issue that caused the overflow to occur.
Great work with this crate btw. very nice to use!

Closes #48

### CODE REVIEW

**Comment by bschwind** [comment]
Hey thanks for the PR! It would seem CI hasn't been run in awhile on this crate, so there are probably things unrelated to your change that are failing as new lints and such get added to clippy.

Let me know if you need any help with that.

Edit - Actually it's probably better if I create a separate PR fixing those issues.

**Comment by bschwind** [comment]
@Nereuxofficial okay, you can rebase your branch on the latest `master` branch to pick up the CI fixes.

As for the overflow fix, I'm still working on reproducing the original issue with the example bytes I gave in that comment 😅

Also, here is the reference pseudocode for decoding variable byte integers, from the [spec](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901011)

```
multiplier = 1
value = 0

do
   encodedByte = 'next byte from stream'
   value += (encodedByte AND 127) * multiplier

   if (multiplier > 128*128*128)
      throw Error(Malformed Variable Byte Integer)

   multiplier *= 128
while ((encodedByte AND 128) != 0)
```

**Comment by Nereuxofficial** [comment]
> @Nereuxofficial okay, you can rebase your branch on the latest `master` branch to pick up the CI fixes.
> 
> As for the overflow fix, I'm still working on reproducing the original issue with the example bytes I gave in that comment 😅
> 
> Also, here is the reference pseudocode for decoding variable byte integers, from the [spec](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901011)
> 
> ```
> multiplier = 1
> value = 0
> 
> do
>    encodedByte = 'next byte from stream'
>    value += (encodedByte AND 127) * multiplier
> 
>    if (multiplier > 128*128*128)
>       throw Error(Malformed Variable Byte Integer)
> 
>    multiplier *= 128
> while ((encodedByte AND 128) != 0)
> ```

Interesting. I still have the fuzzing file available but the example was exactly what was there before the fix. I'll have a look at this again later today

**Comment by Nereuxofficial** [comment]
So these are the bytes crashing the program previously which i just decoded with decode_mqtt
`[255, 255, 255, 255, 255, 255, 255, 255, 255, 254, 255, 53, 127, 255]` 
Here is the test i wrote:
```rust
		let data: &[u8] = &[
            255, 255, 255, 255, 255, 255, 255, 255, 255, 254, 255, 53, 127, 255,
        ];
        decode_mqtt(&mut BytesMut::from(data), ProtocolVersion::V500).unwrap();
```

**Comment by bschwind** [comment]
I think we just need to limit the loop iterations to 4, as a variable byte integer cannot have more than 4 bytes.

And then maybe we don't need the `> 128 * 128 * 128` check at all. Honestly I'm not sure why the pseudocode from the spec is so misleading. Maybe it's assuming the packet has already been validated or something.

```rust
fn decode_variable_int(bytes: &mut Cursor<&mut BytesMut>) -> Result<Option<u32>, DecodeError> {
    let mut multiplier: u32 = 1;
    let mut value: u32 = 0;

    for _ in 0..4 {
        let encoded_byte = read_u8!(bytes);

        value += ((encoded_byte & 0b0111_1111) as u32) * multiplier;

        multiplier *= 128;

        if encoded_byte & 0b1000_0000 == 0b0000_0000 {
            return Ok(Some(value));
        }
    }

    Err(DecodeError::InvalidRemainingLength)
}
```

We should also add a test for this failing scenario to make sure we don't repeat any mistakes.

I can add these changes if you prefer.

**Comment by Nereuxofficial** [comment]
> I think we just need to limit the loop iterations to 4, as a variable byte integer cannot have more than 4 bytes.
> 
> And then maybe we don't need the `> 128 * 128 * 128` check at all. Honestly I'm not sure why the pseudocode from the spec is so misleading. Maybe it's assuming the packet has already been validated or something.
> 
> ```rust
> fn decode_variable_int(bytes: &mut Cursor<&mut BytesMut>) -> Result<Option<u32>, DecodeError> {
>     let mut multiplier: u32 = 1;
>     let mut value: u32 = 0;
> 
>     for _ in 0..4 {
>         let encoded_byte = read_u8!(bytes);
> 
>         value += ((encoded_byte & 0b0111_1111) as u32) * multiplier;
> 
>         multiplier *= 128;
> 
>         if encoded_byte & 0b1000_0000 == 0b0000_0000 {
>             return Ok(Some(value));
>         }
>     }
> 
>     Err(DecodeError::InvalidRemainingLength)
> }
> ```
> 
> We should also add a test for this failing scenario to make sure we don't repeat any mistakes.
> 
> I can add these changes if you prefer.

Yeah me neither, i was trying to make a pure C implementation which would match the spec exactly and try whether it would crash as well and then send that example to OASIS so they may or may not fix that in the spec, because if someone implements it with their reference in C they risk overflowing their int which may be pretty bad.

**Comment by Nereuxofficial** [comment]
Nvm it was another overflow in the program...
As for the mqtt_v5 implementation i'm going to implement your fix right now, thanks so much for your help!

File: mqtt-v5/src/types.rs [hunk 1]
```diff
@@ -34,6 +34,12 @@ pub enum DecodeError {
     BadTransport, // When errors occur on a lower level transport like WS
 }
 
+impl PartialEq for DecodeError {
+    fn eq(&self, other: &Self) -> bool {
+        self == other
```
Comment (bschwind) [inline mqtt-v5/src/types.rs]: I read this and thought "Isn't this recursive?"

Indeed it is, since the `==` operator uses `PartialEq`, so you can't define `PartialEq` in terms of itself.

File: mqtt-v5/src/topic.rs [hunk 2]
```diff
@@ -17,6 +17,13 @@ pub enum TopicFilter {
 
 /// A topic name publishers use when sending MQTT messages.
 /// Cannot contain wildcards.
+///
+/// # Example
+/// ```rust
+/// use std::str::FromStr;
+/// use mqtt_v5::topic::Topic;
+/// let topic = Topic::from_str("my_topic").unwrap();
+/// ```
```
Comment (bschwind) [inline mqtt-v5/src/topic.rs]: I appreciate the documentation, but let's leave this for a separate PR and have this one just focus on fixing the overflow error.

File: mqtt-v5/src/decoder.rs [hunk 3]
```diff
@@ -1293,4 +1287,14 @@ mod tests {
...
     }
+    #[test]
+    fn test_decode_variable_int_crash() {
+        let number: u32 = u32::MAX;
+        assert_eq!(
+            decode_variable_int(&mut Cursor::new(&mut BytesMut::from(
+                number.to_be_bytes().as_slice()
+            ))),
+            Err(DecodeError::InvalidRemainingLength)
+        );
```
Comment (bschwind) [inline mqtt-v5/src/decoder.rs]: Sorry, I know `EncodeError` and `DecodeError` contain `std::io::Error` which doesn't derive `PartialEq`, which in turn makes it hard to derive for those errors as well.

It may be easier to use the `matches!()` macro.

```suggestion
        let number: u32 = u32::MAX;
        let result = decode_variable_int(&mut Cursor::new(&mut BytesMut::from(
            number.to_be_bytes().as_slice(),
        )));

        assert!(matches!(result, Err(DecodeError::InvalidRemainingLength)));
```

Comment (Nereuxofficial) [reply mqtt-v5/src/decoder.rs]: I didn't know about the matches macro, thanks!

**Review by bschwind — APPROVED** [review]
Looks great, thanks for taking this on!
